version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: barber-db
    restart: always
    environment:
      - POSTGRES_USER=felipe
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=barber_shop
    ports:
      - "5432:5432"
